# Generated by Django 3.1.12 on 2021-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.CharField(choices=[('Flower', 'flower'), ('Engine', 'engine'), ('Road', 'road'), ('Calculus', 'calculus'), ('Aero', 'aero'), ('Bearing', 'bearing'), ('Gear', 'gears'), ('Dish', 'dish'), ('Python image', 'python'), ('Shaft', 'shaft')], default='', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
