# Generated by Django 3.1.11 on 2021-05-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210519_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('F', 'flower'), ('E', 'engine'), ('R', 'road'), ('C', 'calculus'), ('A', 'aero'), ('B', 'bearing'), ('G', 'gears')], default='', max_length=50),
        ),
    ]
