# Generated by Django 3.1.11 on 2021-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20210519_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('Flower', 'flower'), ('Engine', 'engine'), ('Road', 'road'), ('Calculus', 'calculus'), ('Aero', 'aero'), ('Bearing', 'bearing'), ('Gear', 'gears'), ('Dish', 'dish'), ('Python image', 'python')], default='', max_length=50),
        ),
    ]
