# Generated by Django 3.1.11 on 2021-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20210519_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('Flower', 'flower'), ('Engine', 'engine'), ('Road', 'road'), ('Calculus', 'calculus'), ('Aero', 'aero'), ('Bearing', 'bearing'), ('Gear', 'gears'), ('Dish', 'dish'), ('Python image', 'python'), ('Shaft', 'shaft')], default='', max_length=50),
        ),
    ]
