# Generated by Django 3.1.11 on 2021-05-26 12:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20210526_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='https://res.cloudinary.com/joboa/image'),
        ),
    ]
